StoreSystem/Models/PrecioProductos.cs
using NuGet.Protocol.Plugins;

namespace StoreSystem.Models
{
    public class PrecioProductos
    {
        public int id_precio { get; set; }
        public int producto_id { get; set; }
        public float precio_unidad { get; set; }
        public DateTime fecha_vigencia { get; set; }
        public DateTime fecha_configuracion { get; set; }
        public int usuario_id { get; set; }
        public int estado { get; set; }

        //Relacionado a otras tabla
        public int id_producto { get; set; }
        public string nombre_producto { get; set; }
        public string correoUsr { get; set; }

    }
}

StoreSystem/Controllers/PrecioProductosController.cs
using Microsoft.AspNetCore.Mvc;
using StoreSystem.Datos;

namespace StoreSystem.Controllers
{
    public class PrecioProductosController : Controller
    {
        public PrecioProductosDatos _PrecioProductosDatos;
        public PrecioProductosController(IConfiguration _configuration)
        {
            _PrecioProductosDatos = new PrecioProductosDatos(_configuration);
        }
        public IActionResult Listar()
        {
            var oLista = _PrecioProductosDatos.Listar();   
            return View(oLista);
        }
    }
}

StoreSystem/Views/PrecioProductos/Listar.cshtml
@model List<PrecioProductos>
    @{
        ViewData["Title"] = "Listar";
        Layout = "~/Views/Shared/_Layout.cshtml";
    }
    <div class="card">
        <div class="card-header">
            Historico de Precio Vigentes
        </div>
        <div class="card-body">

        <a asp-action="Crear" asp-controller="PrecioProductos" class="btn btn-success"><i class="bi bi-person-fill-add"></i> Agregar nuevo precio</a>
            <hr />
            <table class="table table-bordered table-hover">
                <thead>
                    <tr>
                        <th>Codigo</th>
                        <th>Nombre</th>
                        <th>Precio Unidad</th>
                        <th>Fecha De Vigencia</th>
                        <th>Fecha de Creacion</th>
                        <th>usuario que configuro</th>
                        <th>estado</th>

                    </tr>
                </thead>
                <tbody>
                    @if (Model != null)
                    {
                        @foreach (var item in Model)
                        {
                            <tr>
                            <td>@(item.producto_id)</td>
                                <td>@(item.nombre_producto)</td>
                                <td>Q. @(item.precio_unidad)</td>
                                <td>@(item.fecha_vigencia)</td>
                                <td>@(item.fecha_configuracion)</td>
                                <td>@(item.correoUsr)</td>
                                <td>@(item.estado)</td>

     @*                            <td>
                                <a asp-action="Editar" asp-controller="PrecioProductos" class="btn btn-warning btn-sm" asp-route-idProducto="@item.id_producto"><i class="bi bi-pencil-square"></i> Editar</a>
                                </td>
                                <td>
                                <a asp-action="Eliminar" asp-controller="PrecioProductos" class="btn btn-danger btn-sm" asp-route-idProducto="@item.id_producto"><i class="bi bi-trash"></i> Eliminar</a>
                                </td> *@
                            </tr>

                        }
                    }
                </tbody>

            </table>

        </div>
    </div>