StoreSystem/Models/Proveedores.cs
using System.ComponentModel.DataAnnotations;

namespace StoreSystem.Models
{
    public class Proveedores
    {
        public int id_proveedor { get; set; }

        [Required(ErrorMessage = "El Nombre es requerido")]
        public string nombre_proveedor { get; set; }

        [Required(ErrorMessage = "El NIT es requerido")]
        public string nit_proveedor { get; set; }

        [Required(ErrorMessage = "El telefono es requerido")]
        public string telefono_proveedor { get; set; }

        [Required(ErrorMessage = "La Direccion es requerida")]
        public string direccion_proveedor { get; set; }

        [Required(ErrorMessage = "El Correo es requerido")]
        public string correo_proveedor { get; set; }

    }
}

StoreSystem/Controllers/ProveedoresController.cs
using Microsoft.AspNetCore.Mvc;
using StoreSystem.Datos;
using StoreSystem.Models;

namespace StoreSystem.Controllers
{
    public class ProveedoresController : Controller
    {
        public ProveedorDatos _ProveedorDatos;

        public ProveedoresController(IConfiguration _configuration)
        {
            _ProveedorDatos = new ProveedorDatos(_configuration);
        }

        // get: Listar
        public IActionResult Listar()
        {
            var oLista = _ProveedorDatos.Listar();
            return View(oLista);
        }

        public IActionResult Crear()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Crear(Proveedores oProveedor)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }

            var respuesta = _ProveedorDatos.Crear(oProveedor);

            if (respuesta)
            {
                return RedirectToAction("Listar");
            }
            else
            {
                return View();
            }
        }

        public IActionResult Editar(int idProveedor)
        {
            var oProveedor = _ProveedorDatos.Buscar(idProveedor);

            return View(oProveedor);
        }

        [HttpPost]
        public IActionResult Editar(Proveedores oProveedor)
        {
            if (!ModelState.IsValid)
                return View();

            var respuesta = _ProveedorDatos.Editar(oProveedor);

            if (respuesta)
                return RedirectToAction("Listar");
            else
                return View();
        }

        public IActionResult Eliminar(int idProveedor)
        {
            var oProveedor = _ProveedorDatos.Buscar(idProveedor);

            return View(oProveedor);
        }

        [HttpPost]
        public IActionResult Eliminar(Proveedores oProveedor)
        {
            var respuesta = _ProveedorDatos.Eliminar(oProveedor);

            if (respuesta)
                return RedirectToAction("Listar");
            else
                return View();
        }

    }
}

StoreSystem/Views/Proveedores/Crear.cshtml
@model Proveedores
@{
    ViewData["Title"] = "Crear";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="card">
    <div class="card-header">
        Crear Proveedor
    </div>
    <div class="card-body">

        <form asp-action="Crear" asp-controller="Proveedores" method="post">


            <div class="mb-3">
                <label class="form-label">Nombre</label>
                <input asp-for="nombre_proveedor" type="text" class="form-control">
                <span asp-validation-for="nombre_proveedor" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label class="form-label">NIT</label>
                <input asp-for="nit_proveedor" type="text" class="form-control">
                <span asp-validation-for="nit_proveedor" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label class="form-label">Telefono</label>
                <input asp-for="telefono_proveedor" type="text" class="form-control">
                <span asp-validation-for="telefono_proveedor" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label class="form-label">Direccion</label>
                <input asp-for="direccion_proveedor" type="text" class="form-control">
                <span asp-validation-for="direccion_proveedor" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label class="form-label">Correo</label>
                <input asp-for="correo_proveedor" type="text" class="form-control">
                <span asp-validation-for="correo_proveedor" class="text-danger"></span>
            </div>



            <button type="submit" class="btn btn-primary"><i class="bi bi-person-up"></i> Guardar</button>
            <a asp-action="Listar" asp-controller="Proveedores" class="btn btn-warning"><i class="bi bi-list-ul"></i> Volver a la lista</a>
        </form>


    </div>
</div>

StoreSystem/Views/Proveedores/Editar.cshtml
@model Proveedores
@{
    ViewData["Title"] = "Editar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="card">
    <div class="card-header">
        Editar Proveedor
    </div>
    <div class="card-body">

        <form asp-action="Editar" asp-controller="Proveedores" method="post">

            <input asp-for="id_proveedor" type="hidden" class="form-control">

            <div class="mb-3">
                <label class="form-label">Nombre</label>
                <input asp-for="nombre_proveedor" type="text" class="form-control">
                <span asp-validation-for="nombre_proveedor" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label class="form-label">NIT</label>
                <input asp-for="nit_proveedor" type="text" class="form-control">
                <span asp-validation-for="nit_proveedor" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label class="form-label">Telefono</label>
                <input asp-for="telefono_proveedor" type="text" class="form-control">
                <span asp-validation-for="telefono_proveedor" class="text-danger"></span>
            </div>

            <div class="mb-3">
                <label class="form-label">Direccion</label>
                <input asp-for="direccion_proveedor" type="text" class="form-control">
                <span asp-validation-for="direccion_proveedor" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label class="form-label">Correo</label>
                <input asp-for="correo_proveedor" type="text" class="form-control">
                <span asp-validation-for="correo_proveedor" class="text-danger"></span>
            </div>


            <button type="submit" class="btn btn-primary"><i class="bi bi-pencil-square"></i> Actualizar</button>
            <a asp-action="Listar" asp-controller="Proveedores" class="btn btn-warning"> <i class="bi bi-list-ul"></i> Volver a la lista</a>
        </form>


    </div>
</div>

StoreSystem/Views/Proveedores/Eliminar.cshtml
@model Proveedores
@{
    ViewData["Title"] = "Eliminar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="card">
    <div class="card-header">
        Eliminar Proveedor
    </div>
    <div class="card-body">

        <form asp-action="Eliminar" asp-controller="Proveedores" method="post">

            <input asp-for="id_proveedor" type="hidden" class="form-control">


            <div class="alert alert-danger" role="alert">
                ¿Desea Eliminar al Proveedor: @Html.DisplayTextFor(m => m.nombre_proveedor) ?
            </div>


            <button type="submit" class="btn btn-primary"><i class="bi bi-trash"></i> Eliminar</button>
            <a asp-action="Listar" asp-controller="Proveedores" class="btn btn-warning"> <i class="bi bi-list-ul"></i> Volver a la lista</a>
        </form>
    </div>
</div>

StoreSystem/Views/Proveedores/Listar.cshtml
@model List<Proveedores>
@{
    ViewData["Title"] = "Listar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="card">
    <div class="card-header">
        Listar Proveedores
    </div>
    <div class="card-body">

        <a asp-action="Crear" asp-controller="Proveedores" class="btn btn-success"><i class="bi bi-person-fill-add"></i> Crear Nuevo</a>
        <hr />
        <table class="table table-bordered table-hover">
            <thead>
                <tr>
                    <th>Nombre</th>
                    <th>NIT</th>
                    <th>Telefono</th>
                    <th>Direccion</th>
                    <th>Correo</th>

                    <th>Acciones</th>
 
                </tr>
            </thead>
            <tbody>
                @if (Model != null)
                {
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>@(item.nombre_proveedor)</td>
                            <td>@(item.nit_proveedor)</td>
                            <td>@(item.telefono_proveedor)</td>
                            <td>@(item.direccion_proveedor)</td>
                            <td>@(item.correo_proveedor)</td>

                            <td>
                                <a asp-action="Editar" asp-controller="Proveedores" class="btn btn-warning btn-sm" asp-route-idProveedor="@item.id_proveedor"><i class="bi bi-pencil-square"></i> Editar</a>
                            </td>
                            <td>
                                <a asp-action="Eliminar" asp-controller="Proveedores" class="btn btn-danger btn-sm" asp-route-idProveedor="@item.id_proveedor"><i class="bi bi-trash"></i> Eliminar</a>
                            </td>
                        </tr>

                    }
                }
            </tbody>

        </table>

    </div>
</div>