StoreSystem/Models/Ingresos.cs
using System.ComponentModel.DataAnnotations;

namespace StoreSystem.Models
{
	public class Ingresos
	{
		public int id_ingreso { get; set; }
		public string compra_id { get; set; }

        [Required(ErrorMessage = "El campo cantidad ingreso es obligatorio.")]
        public int producto_id { get; set; }

        [Required(ErrorMessage = "El campo cantidad ingreso es obligatorio.")]
        public int cantidad_ingreso { get; set; }

        [Required(ErrorMessage = "El campo costo de ingreso es obligatorio.")]
        public float costo_ingreso { get; set; }

        [Required(ErrorMessage = "El campo Fecha de Vencimiento es obligatorio.")]
        public DateTime fecha_vencimiento { get; set; }

		public string comentario_ingreso { get; set; }

        // ingreso de parametros automaticos
        public DateTime fecha_ingreso { get; set; }
		public int usuario_id { get; set; }



		//Relacionado a tabla de productos
		public int id_producto { get; set; }
		public string nombre_producto { get; set; }

        public string correoUsr {  get; set; }  
	}
}

StoreSystem/Controllers/IngresosController.cs
using Microsoft.AspNetCore.Mvc;
using StoreSystem.Datos;
using StoreSystem.Models;

namespace StoreSystem.Controllers
{
	public class IngresosController : Controller
	{
		public IngresosDatos _IngresosDatos;
		public DatosDTO _DatosDTOProd;
		public IngresosController(IConfiguration _configuration)
		{
			_IngresosDatos = new IngresosDatos(_configuration);
			_DatosDTOProd = new DatosDTO(_configuration);	
		}

		public IActionResult Crear()
		{
            var LProductos = _DatosDTOProd.ListarProductos();

			ViewBag.oProductos = LProductos;

            return View();
		}

		[HttpPost]
		public IActionResult Crear(Ingresos oIngresos) 
		{

            var respuesta = _IngresosDatos.Crear(oIngresos);

			if (respuesta)
			{
				return RedirectToAction("MostrarExistencias","Existencias");
			}
			else
			{
				return View();
			}
		}

		public IActionResult Listar() 
		{
			var oLista = _IngresosDatos.Listar();
			return View(oLista);	
		}

	}
}

StoreSystem/Controllers/ProductosController.cs
using Microsoft.AspNetCore.Mvc;
using StoreSystem.Datos;
using StoreSystem.Models;
using System.Data;
using System.Reflection;
using System.Security.Cryptography;
using System;

namespace StoreSystem.Controllers
{
    public class ProductosController : Controller
    {
        public ProductosDatos _ProductosDatos;
        public DatosDTO _DatosDTOProv;
        public DatosDTO _DatosDTOCat;

        public ProductosController(IConfiguration _configuration) 
        {
            _ProductosDatos = new ProductosDatos(_configuration);    
            _DatosDTOProv = new DatosDTO(_configuration); 
            _DatosDTOCat  = new DatosDTO(_configuration);
        }

        public IActionResult Listar()
        {
            var oLista = _ProductosDatos.Listar();
            return View(oLista);
        }

        public IActionResult Crear()
        {
            var LProveedores = _DatosDTOProv.ListarProveedores();
            var LCategorias  = _DatosDTOCat.ListarCategorias();

            ViewBag.oProveedores = LProveedores;
            ViewBag.oCategorias = LCategorias;

            return View();
        }

        [HttpPost]
        public IActionResult Crear(Productos oProducto)
        {

            var respuesta = _ProductosDatos.Crear(oProducto);

            if (respuesta)
            {
                return RedirectToAction("Listar");
            }
            else
            {
                return View();
            }
        }

        public IActionResult Editar(int idProducto)
        {
            var oProducto = _ProductosDatos.Buscar(idProducto);
            

            var LProveedores = _DatosDTOProv.ListarProveedores();
            var LCategorias  = _DatosDTOCat.ListarCategorias();

            ViewBag.oProveedores = LProveedores;
            ViewBag.oCategorias = LCategorias;

            return View(oProducto);
        }

        [HttpPost]
        public IActionResult Editar(Productos oProducto)
        {

            var respuesta = _ProductosDatos.Editar(oProducto);

            if (respuesta)
                return RedirectToAction("Listar");
            else
                return View();
        }

        public IActionResult Eliminar(int idProducto)
        {
            var oProducto = _ProductosDatos.Buscar(idProducto);

            return View(oProducto);
        }

        [HttpPost]
        public IActionResult Eliminar(Productos oProducto)
        {
            var respuesta = _ProductosDatos.Eliminar(oProducto);

            if (respuesta)
                return RedirectToAction("Listar");
            else
                return View();
        }


    }
}

StoreSystem/Views/Ingresos/Crear.cshtml
@using System.Text.Json
@using System.Security.Claims
@model Ingresos
@{
    ViewData["Title"] = "Crear";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@{
    var currentUser = Context.User.Identity as ClaimsIdentity;
    var userName = currentUser?.FindFirst(ClaimTypes.Email)?.Value;
    var userID = currentUser?.FindFirst(ClaimTypes.NameIdentifier)?.Value;
}

<div class="card">
    <div class="card-header">
        Ingreso de productos a inventario
    </div>
    <div class="card-body">

        <form asp-action="Crear" asp-controller="Ingresos" method="post">

            <div class="mb-3">
                <label class="form-label"># Orden de compra</label>
                <input asp-for="compra_id" type="text" class="form-control" required>
                <span asp-validation-for="compra_id" class="text-danger"></span>
            </div>

            <div class="mb-3">
                <label class="form-label">Producto a ingresar</label>
                <select class="form-control form-control-sm" asp-for="producto_id" required>
                    <option value="0">[Seleccione un Producto]</option>

                    @if (@ViewBag.oProductos != null)
                    {
                        @foreach (var item1 in @ViewBag.oProductos)
                        {
                            <option value="@(item1.id_producto)">@item1.nombre_producto</option>
                        }
                    }
                </select>
            </div>

            <div class="mb-3">
                <label class="form-label">Cantidad de unidades</label>
                <input asp-for="cantidad_ingreso" type="number" class="form-control" min="1" required>
                <span asp-validation-for="cantidad_ingreso" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label class="form-label">Costo de unidad </label>
                <input asp-for="costo_ingreso" type="number" class="form-control" min="0" step="0.01" required>
                <span asp-validation-for="costo_ingreso" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label class="form-label">Fecha de vencimiento</label>
                <input asp-for="fecha_vencimiento" type="date" class="form-control" required>
                <span asp-validation-for="fecha_vencimiento" class="text-danger"></span>
            </div>

            <div class="mb-3">
                <label class="form-label">comentarios del ingreso</label>
                <input asp-for="comentario_ingreso" type="text" class="form-control" required>
                <span asp-validation-for="comentario_ingreso" class="text-danger"></span>
            </div>

            <div class="mb-3">
                <label class="form-label">Usuario que registra</label>
                <select class="form-control form-control-sm" asp-for="usuario_id">
                    <option value="@userID">@userName</option>
                </select>
            </div>

            <button type="submit" class="btn btn-primary"><i class="bi bi-person-up"></i> Guardar</button>
            <a asp-action="Listar" asp-controller="Ingresos" class="btn btn-warning"><i class="bi bi-list-ul"></i> Volver a la lista</a>
        </form>

    </div>
</div>


@section Scripts {
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validation/1.19.3/jquery.validate.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validation-unobtrusive/3.2.12/jquery.validate.unobtrusive.min.js"></script>

    <script>
        document.addEventListener('DOMContentLoaded', function () {
            document.querySelector('form').addEventListener('submit', function (e) {
                var selectedValue = document.querySelector('select[name="producto_id"]').value;
                if (selectedValue === '0') {
                    e.preventDefault();
                    alert('Por favor, seleccione un producto válido.');
                }
            });
        });
    </script>

}

StoreSystem/Views/Ingresos/Listar.cshtml
@model List<Ingresos>
@{
    ViewData["Title"] = "Listar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="card">
    <div class="card-header">
        Productos Ingresados a inventario
    </div>
    <div class="card-body">

        <a asp-action="Crear" asp-controller="Ingresos" class="btn btn-success"><i class="bi bi-person-fill-add"></i> Ingresar Productos a Inventario</a>
        <hr />
        <table class="table table-bordered table-hover">
            <thead>
                <tr>
                    <th>Orden Compra</th>
                    <th>Producto</th>
                    <th>Cantidad</th>
                    <th>Costo</th>
                    <th>Vencimiento</th>
                    <th>Comentarios</th>
                    <th>Ingreso</th>
                    <th>Registró</th>

                </tr>
            </thead>
            <tbody>
                @if (Model != null)
                {
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>@(item.compra_id)</td>
                            <td>@(item.nombre_producto)</td>
                            <td>@(item.cantidad_ingreso)</td>
                            <td>Q. @(item.costo_ingreso)</td>
                            <td>@(item.fecha_vencimiento)</td>
                            <td>@(item.comentario_ingreso)</td>
                            <td>@(item.fecha_ingreso)</td>
                            <td>@(item.correoUsr)</td>

@*                             <td>
                                <a asp-action="Editar" asp-controller="Productos" class="btn btn-warning btn-sm" asp-route-idProducto="@item.id_producto"><i class="bi bi-pencil-square"></i> Editar</a>
                            </td>
                            <td>
                                <a asp-action="Eliminar" asp-controller="Productos" class="btn btn-danger btn-sm" asp-route-idProducto="@item.id_producto"><i class="bi bi-trash"></i> Eliminar</a>
                            </td> *@
                        </tr>

                    }
                }
            </tbody>

        </table>

    </div>
</div>