StoreSystem/Models/Caja.cs
using System.Security.Policy;

namespace StoreSystem.Models
{
    public class Caja
    {
        public int id_caja { get; set; }
        public float MontoInicial { get; set; }
        public DateTime fecha_apertura { get; set; }
        public DateTime? fecha_cierre { get; set; }
        public string estado_caja { get; set; }
        public int usuario_id { get; set; }

        //relacionado a otras tablas
        public string correoUsr { get; set; }

    }
}

StoreSystem/Controllers/CajaController.cs
using Microsoft.AspNetCore.Mvc;
using StoreSystem.Datos;
using StoreSystem.Models;
using System.Security.Claims;

namespace StoreSystem.Controllers
{
    public class CajaController : Controller
    {
        public CajaDatos _CajaDatos;

        public CajaController(IConfiguration _configuration)
        {
            _CajaDatos = new CajaDatos(_configuration);
        }
        public IActionResult estados()
        {
            var oLista = _CajaDatos.Estados();
            return View(oLista);
        }
        public IActionResult Crear()
        {
            // Metodo que solo devuelve la vista
            return View();
        }

        [HttpPost]
        public IActionResult Crear(Caja oCaja)
        {

            // Metodo que recibe el objeto para guardarlo en DB
            var respuesta = _CajaDatos.Crear(oCaja);

            if (respuesta)
            {
                return RedirectToAction("Estados");
            }
            else
                return View();
        }

        public IActionResult Editar(int idcaja)
        {
            var ocaja = _CajaDatos.Buscar(idcaja);

            // Metodo que solo devuelve la vista
            return View(ocaja);
        }

        [HttpPost]
        public IActionResult Editar(Caja oCaja)
        {

            // Metodo que recibe el objeto para guardarlo en DB
            var respuesta = _CajaDatos.Editar(oCaja);

            if (respuesta)
            {
                return RedirectToAction("estados");
            }
            else
                return View();
        }


    }
}

StoreSystem/Views/Caja/Crear.cshtml
@using System.Text.Json
@using System.Security.Claims
@model Caja
@{
    ViewData["Title"] = "Crear";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@{
    var currentUser = Context.User.Identity as ClaimsIdentity;
    var userName = currentUser?.FindFirst(ClaimTypes.Email)?.Value;
    var userID = currentUser?.FindFirst(ClaimTypes.NameIdentifier)?.Value;
}

<div class="card">
    <div class="card-header">
        APERTURA DE CAJA
    </div>
    <div class="card-body">

        <form asp-action="Crear" asp-controller="Caja" method="post">


            <div class="mb-3">
                <label class="form-label">Fondo Inicial </label>
                <input asp-for="MontoInicial" type="number" class="form-control" min="0" step="0.01" required>
                <span asp-validation-for="MontoInicial" class="text-danger"></span>
            </div>

            <div class="mb-3">
                <label class="form-label">Usuario al que se asigna la apertura de caja</label>
                <select class="form-control form-control-sm" asp-for="usuario_id">
                    <option value="@userID">@userName</option>
                </select>
            </div>

            <button type="submit" class="btn btn-primary"><i class="bi bi-person-up"></i> Aperturar Caja</button>
            <a asp-action="Estados" asp-controller="Caja" class="btn btn-warning"><i class="bi bi-list-ul"></i> Volver a la lista</a>
        </form>

    </div>
</div>

StoreSystem/Views/Caja/Editar.cshtml
@model Caja
@{
    ViewData["Title"] = "Editar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="card">
    <div class="card-header">
        Cerrar Corte de Caja
    </div>
    <div class="card-body">

        <form asp-action="Editar" asp-controller="Caja" method="post">

            <input asp-for="id_caja" type="hidden" class="form-control">

            <div class="alert alert-danger" role="alert">
                ¿Desea cerrar el corte de caja numero: @Html.DisplayTextFor(m => m.id_caja) ?
            </div>


            <button type="submit" class="btn btn-danger"><i class="bi bi-pencil-square"></i> Cerrar</button>
            <a asp-action="estados" asp-controller="Caja" class="btn btn-warning"> <i class="bi bi-list-ul"></i> Volver a la lista</a>
        </form>


    </div>
</div>

StoreSystem/Views/Caja/estados.cshtml
@model List<Caja>
@{
    ViewData["Title"] = "Listar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="card">
    <div class="card-header">
        Aperturas de Caja
    </div>
    <div class="card-body">

        <a asp-action="Crear" asp-controller="Caja" class="btn btn-success"><i class="bi bi-person-fill-add"></i> Apertura de Caja</a>

        <hr />
        <table class="table table-bordered table-hover">
            <thead>
                <tr>
                    <th># Apertura.</th>
                    <th>Fondo Inicial</th>
                    <th>Fecha de apertura</th>
                    <th>Fecha de Cierre</th>
                    <th>Estado de caja</th>
                    <th>usuario que aperturo</th>
                    <th>Acciones</th>

                </tr>
            </thead>
            <tbody>
                @if (Model != null)
                {
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>@(item.id_caja)</td>
                            <td>Q. @(item.MontoInicial)</td>
                            <td>@(item.fecha_apertura)</td>
                            <td>@(item.fecha_cierre == null ? "Caja abierta" : item.fecha_cierre.ToString())</td>
                            <td>@(item.estado_caja)</td>
                            <td>@(item.correoUsr)</td>
                            <td>
                                <a asp-action="Editar" asp-controller="Caja" class="btn btn-danger btn-sm" asp-route-idcaja="@item.id_caja"><i class="bi bi-pencil-square"></i> Cerrar Caja</a>

                            </td>

                        </tr>

                    }
                }
            </tbody>

        </table>

    </div>
</div>

<!-- Modal Trigger -->
<a class="waves-effect waves-light btn modal-trigger" href="#modal1">Modal</a>

<!-- Modal Structure -->
<div id="modal1" class="modal">
    <div class="modal-content">
        <h4>Modal Header</h4>
        <p>A bunch of text</p>
    </div>
    <div class="modal-footer">
        <a href="#!" class="modal-close waves-effect waves-green btn-flat">Agree</a>
    </div>
</div>